<?php

/**
 * @file
 * OLAP primary module file.
 */

/**
 * Implements hook_menu().
 */
function olap_menu() {
  $items['admin/content/olap'] = array(
    'title' => 'OLAP',
    'page callback' => 'olap_report',
    'access arguments' => array('access olap'),
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'file' => 'olap.admin.inc',
  );

  return $items;
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function olap_form_olap_form_alter(&$form, &$form_state) {
  $form['form_build_id']['#access'] = FALSE;
  $form['form_token']['#access'] = FALSE;
  $form['form_id']['#access'] = FALSE;
}
